# This file was generated by GoReleaser. DO NOT EDIT.
cask "pronto" do
  version "0.0.5"

  on_macos do
    on_arm do
      sha256 "d91d6fd708daa6ef603f557b73cc872c586dc2994bfdf4c23d1c2d4aa04ef09b"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0a90b1aee1a2168887cb65663188d0bc3c1a51b02e180546ced6c542a61b920"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e912568c43d18e315719e76b8aad575b39cefbd5021925df8adb14dca4dcf257"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3bc311985399a51ba0a0c32d0bd50f94165cac09fc0deb07e2c6b155dde4c351"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pronto"
  desc "PR triage dashboard and review queue"
  homepage "https://github.com/kalverra/pronto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pronto"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pronto"]
    end
  end

  # No zap stanza required
end
