# This file was generated by GoReleaser. DO NOT EDIT.
cask "pronto" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f8190e38bc5f80d3e75c5d8f16ad91e51924dfa3a17b1bc210015c579c1d6d9a"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "af46866962c34f1f8e4f26bb0342e81d889b50c026500f14997f16279884e642"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cf995499b60636a0bdce4a210d78ece40b1f7778baad0e7eaa8bf4bea8c07405"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b85216c2a3787192fdfc4dd52716a417315b8b1cf33f115bd0ba2a22de6b143"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pronto"
  desc "PR triage dashboard and review queue"
  homepage "https://github.com/kalverra/pronto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pronto"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pronto"]
    end
  end

  # No zap stanza required
end
