# This file was generated by GoReleaser. DO NOT EDIT.
cask "pronto" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "796e01770f26beb28e7380e3eea6ba72d4a35d927dbf81ba0c24ddfb528d38d5"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a85c5c028fef60dada27a35a5c4bdee449667926e54337748ed20ed564ab88a"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d1cf58c63ab6eac5f949362e53abd16242e7b95ae1673ffc5f9e8d99a8dd8cd3"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "00b1b968bd5366ab26151c73326ad0c4a225d20f46e73329d834121345697acd"
      url "https://github.com/kalverra/pronto/releases/download/v#{version}/pronto_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pronto"
  desc "PR triage dashboard and review queue"
  homepage "https://github.com/kalverra/pronto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pronto"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pronto"]
    end
  end

  # No zap stanza required
end
